### ISSUE TITLE
error with new instant os beta2 iso based on arch 

### ISSUE THREAD

**Issue by mchasard** [instantOS/instantARCH#1]
i tried to install under vbox the new instantOs based on archlinux instead of manjaro but at the end of install i got an error ... access denied 

after that i'm able to boot but when i try to sign me under lightdm , an error occured and no way to enter

so i created a new user but same issue no way i can't sign me ...

**Comment by paperbenni** [comment]
Can you post a screenshot of that error? Any log files?

**Comment by paperbenni** [comment]
Oh, and which locale did you select? It might be related to that.

**Comment by mchasard** [comment]
hi forgot to make a screenshot sorry about locale it was fr french

**Comment by mchasard** [comment]
so i have reinstall with another locale ?  with the previous version beta 1 under manjaro i had no such issue

**Comment by paperbenni** [comment]
I just reproduced the error and pushed a fix. The installer is auto updating, so you can reinstall with the same iso.

**Comment by paperbenni** [comment]
I just tested a french install, worked. It should be fixed now, including all other languages that could've been affected.

**Comment by mchasard** [comment]
OK thanks but how can I apply the fix ?

**Comment by paperbenni** [comment]
You don't have to do anything, just boot up the installer and install like before. It automatically fetches any updates to the installer.

**Comment by mchasard** [comment]
Thanks paperbenni , finally i could install it , i have the feeling that under arch , its more speed...
i like this new different distro ,  hope it could be support for long time

**Comment by paperbenni** [comment]
Good to hear :)
