### ISSUE TITLE
Problem with importing PGP Key

### ISSUE THREAD

**Issue by Cloufish** [instantOS/instantARCH#15]
Hi, I'm trying to install instantOS on a 32bit really old Laptop with CLI installation. But there're issues I'm encountering:

1. I need to use --insecure flag with curl to download the script, because the laptop can't establish secure connection
2. When I launch the script, there's a PGP Key import error that is looped
I changed keyserver with in `~/.gnupg/dirmngr.conf`
to `keyserver hkp://keyserver.ubuntu.com`
And when I run:
```
gpg --recv-keys C8E8F5A0AF9BA7E7

gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: General error
```

4. When I cancel the installation with Ctrl^Z and try to run the script again after some troubleshooting I get errors regarding notify-send

**Comment by paperbenni** [comment]
instantOS for 32 bit is currently unmaintained and the version is very old. That said, this seems like the iso you are installing from is so old that it is lacking current ssl root certificates, so your problem might just be solved by using a newer iso

**Comment by paperbenni** [comment]
i have made the decision to not repair 32 bit support as it would increase time spent on testing significantly and 32 bit machines are dying out
