### ISSUE TITLE
Dual Boot Support

### ISSUE THREAD

**Issue by happyori** [instantOS/instantARCH#2]
Currently from my attempt at installing instantOS on my dual booting laptop, I see that there is no dual boot support, because the installer doesn't ask me for a partion and rather is asking for a whole drive. Maybe I am missing something (wouldn't be surprised there :upside_down_face:). Is there any way to run installer like an arch install purely through cli, I see the cli installer but from what it says on the page its identical to graphical one (didn't test that yet). I really want to try it out however I can't use up all of my drive on it.

**Comment by paperbenni** [comment]
Dual booting support is not yet present, but you will be able to manually select partitions or automatically set up dual booting.

**Comment by paperbenni** [comment]
There now is support for manual partitioning, meaning that you can select a root partition and optional home and swap partitions. 
Automatically resizing an existing system is not supported yet but you can either set up some partitions beforehand or edit them from the installer
