### ISSUE TITLE
Install script hangs on hard drive selection

### ISSUE THREAD

**Issue by jcstill** [instantOS/instantARCH#9]
I have been trying to install using the CLI version of the installer in a KVM/QEMU VM with both:

`bash <(curl -L raw.githubusercontent.com/instantOS/instantARCH/master/archinstall.sh)`
and
`bash <(curl -L instantos.io/install)`
(looking at them, they seem to be the same)

every time, the installer gets stuck on selecting the hard drive and won't exit:
![instantos-disk](https://user-images.githubusercontent.com/31301328/89358281-c606ad00-d677-11ea-8d9b-91c820158966.png)
Pressing enter on either option loops the script and typing "yes" or "no" has the same result

Pressing control+c has no effect so I have been resetting the VM to try again.

Side Note:
This also happens if I select "no" when it asks if it is a VM:
![instantos-vm](https://user-images.githubusercontent.com/31301328/89358460-38778d00-d678-11ea-9f7c-ac84dc9917ec.png)

**Comment by paperbenni** [comment]
this should now be fixed
